version: '3'
services:
  web:
    build: ./ui
    volumes:
      - ./ui:/app/web
    ports:
      - 3000:3000
    depends_on:
      - searchEngine
      - factCuration
  search-engine:
    build: ./server/searchEngine
    volumes:
      - ./server/searchEngine:/app/searchEngine
    ports:
      - 8080:8080
  fact-curation:
    build: ./server/factCuration
    volumes:
      - ./server/factCuration:/app/factCuration
    ports:
      - 8081:8081